// <auto-generated />
using Guard.Emegenler.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Emegenler.Migrations
{
    [DbContext(typeof(EmegenlerDbContext))]
    partial class EmegenlerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Emegenler.Domains.Models.EmegenlerPolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthRole");

                    b.Property<int>("PolicyElement");

                    b.Property<string>("PolicyElementSelector");

                    b.Property<int>("RoleId");

                    b.Property<string>("UserIdentifier");

                    b.HasKey("PolicyId");

                    b.ToTable("EmegenlerPolicies");
                });

            modelBuilder.Entity("Emegenler.Domains.Models.EmegenlerRole", b =>
                {
                    b.Property<int>("RoledId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName");

                    b.HasKey("RoledId");

                    b.ToTable("EmegenlerRoles");
                });

            modelBuilder.Entity("Emegenler.Domains.Models.EmegenlerUserRoleIdentifier", b =>
                {
                    b.Property<int>("RoleIdentifierId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoleId");

                    b.Property<string>("UserIdentifier");

                    b.HasKey("RoleIdentifierId");

                    b.ToTable("EmegenlerUserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
