// <auto-generated />
using EmegenlerTests.FakeContext;
using FluentAssertions;
using Guard.Emegenler.Domains.Models;
using Guard.Emegenler.MethodReturner;
using Guard.Emegenler.UnitOfWork.Repositories;
using System.Collections.Generic;
using System.Linq;
using TechTalk.SpecFlow;
using Xunit;

namespace EmegenlerTests.RepositoryTests
{
    [Binding]
    [Collection("Sequential")]
    public class EmegenlerPolicyRepositorySteps
    {
        private readonly EmegenlerPolicyRepository repo;
        Returner<EmegenlerPolicy> result;
        Returner<IList<EmegenlerPolicy>> results;
        Returner<long> CountOfPolicies;

        public EmegenlerPolicyRepositorySteps()
        {
            FakeContextGenerator fContextGenerate = new FakeContextGenerator();
            repo = new EmegenlerPolicyRepository(fContextGenerate.GetContext());

        }
        [When(@"We pass new EmegenlerPolicy entity to our Insert method with zero id on entity")]
        public void WhenWePassNewEmegenlerPolicyEntityToOurInsertMethodWithZeroİdOnEntity()
        {
            EmegenlerPolicy policy = new EmegenlerPolicy
            {
                PolicyElement = "Button",
                PolicyElementIdentifier = "canc",
                AccessProtocol = "Readonly",
                AuthBase = Guard.Emegenler.FluentInterface.Policy.Types.AuthBase.User,
                AuthBaseIdentifier = "1",
            };
            result = repo.Insert(policy);
        }

        [Then(@"Insert method should add new EmegenlerPolicy entity to db return with success and new EmegenlerPolicy entity")]
        public void ThenInsertMethodShouldAddNewEmegenlerPolicyEntityToDbReturnWithSuccessAndNewEmegenlerPolicyEntity()
        {
            result.IsSuccess().Should().BeTrue();
        }

        [When(@"We pass EmegenlerPolicy entity with non zero id to our Insert method")]
        public void WhenWePassEmegenlerPolicyEntityWithNonZeroİdToOurInsertMethod()
        {
            EmegenlerPolicy policy = new EmegenlerPolicy
            {
                PolicyId = 1000,
                PolicyElement = "Button",
                PolicyElementIdentifier = "canc",
                AccessProtocol = "Readonly",
                AuthBase = Guard.Emegenler.FluentInterface.Policy.Types.AuthBase.User,
                AuthBaseIdentifier = "1",
            };
            result = repo.Insert(policy);
        }

        [Then(@"Insert method should edit EmegenlerPolicy and save to db after that should return success with updated EmegenlerPolicy entity")]
        public void ThenInsertMethodShouldEditEmegenlerPolicyAndSaveToDbAfterThatShouldReturnSuccessWithUpdatedEmegenlerPolicyEntity()
        {
            result.IsSuccess().Should().BeTrue();
        }

        [When(@"We pass null value to Insert method")]
        public void WhenWePassNullValueToInsertMethod()
        {
            result = repo.Insert(null);
        }

        [Then(@"Insert method should throw NullReferenceException")]
        public void ThenInsertMethodShouldThrowNullReferenceException()
        {
            result.IsFail().Should().BeTrue();
            result.GetException().Should().NotBeNull();
        }
        [When(@"We pass valid EmegenlerPolicyId to Get method")]
        public void WhenWePassValidEmegenlerPolicyIdToGetMethod()
        {
            result = repo.Get(1000);
        }

        [Then(@"Get method should return valid EmegenlerPolicy entity with result success on valid EmegenlerPolicyId")]
        public void ThenGetMethodShouldReturnValidEmegenlerPolicyEntityWithResultSuccessOnValidEmegenlerPolicyId()
        {
            result.IsSuccess().Should().BeTrue();
            result.GetData().Should().NotBeNull();
        }

        [When(@"We pass zero value as EmegenlerPolicyId to Get method")]
        public void WhenWePassZeroValueAsEmegenlerPolicyIdToGetMethod()
        {
            result = repo.Get(0);
        }

        [Then(@"Get method should return state is fail and return Exception on EmegenlerPolicyId is zero")]
        public void ThenGetMethodShouldReturnStateİsFailAndReturnExceptionOnEmegenlerPolicyIdİsZero()
        {
            result.IsSuccess().Should().BeFalse();
            result.IsFail().Should().BeTrue();
            result.GetException().Should().NotBeNull();
            result.GetData().Should().BeNull();
        }

        [When(@"We pass negative value as EmegenlerPolicyId to Get method")]
        public void WhenWePassNegativeValueAsEmegenlerPolicyIdToGetMethod()
        {
            result = repo.Get(-1);
        }

        [Then(@"Get method should return state is fail and return Exception on EmegenlerPolicyId is negative")]
        public void ThenGetMethodShouldReturnStateİsFailAndReturnExceptionOnEmegenlerPolicyIdİsNegative()
        {
            result.IsSuccess().Should().BeFalse();
            result.IsFail().Should().BeTrue();
            result.GetException().Should().NotBeNull();
            result.GetData().Should().BeNull();
        }

        [When(@"We pass valid id value as EmegenlerPolicyId to Get valid EmegenlerPolicyId from Get method")]
        public void WhenWePassValidİdValueAsEmegenlerPolicyIdToGetValidEmegenlerPolicyIdFromGetMethod()
        {
            result = repo.Get(45);
        }

        [Then(@"Get method should return state is fail and return KeyNotFoundException on EmegenlerPolicyId is valid but record not found in our database")]
        public void ThenGetMethodShouldReturnStateİsFailAndReturnKeyNotFoundExceptionOnEmegenlerPolicyIdİsValidButRecordNotFoundİnOurDatabase()
        {
            result.IsSuccess().Should().BeFalse();
            result.IsFail().Should().BeTrue();
            result.GetException().Should().NotBeNull();
            result.GetData().Should().BeNull();
        }

        [When(@"We pass valid page and pageSize take method on EmegenlerPolicyRepository")]
        public void WhenWePassValidPageAndPageSizeTakeMethodOnEmegenlerPolicyRepository()
        {
            results = repo.Take(1, 1);
        }

        [Then(@"Take method should return List of EmegenlerPolicy entites from EmegenlerPolicyRepository")]
        public void ThenTakeMethodShouldReturnListOfEmegenlerPolicyEntitesFromEmegenlerPolicyRepository()
        {
            results.IsSuccess().Should().BeTrue();
            results.GetData().Count().Should().BeGreaterThan(0);

        }


        [When(@"We pass valid page attirubute but pageSize attirubute value is zero on EmegenlerPolicyRepository's Take method")]
        public void WhenWePassValidPageAttirubuteButPageSizeAttirubuteValueİsZeroOnEmegenlerPolicyRepositorySTakeMethod()
        {
            results = repo.Take(1, 0);
        }

        [Then(@"Take method should return fail status and should return Exception on zero value with pageSize attiribute from EmegenlerPolicyRepository")]
        public void ThenTakeMethodShouldReturnFailStatusAndShouldReturnExceptionOnZeroValueWithPageSizeAttiributeFromEmegenlerPolicyRepository()
        {
            results.IsSuccess().Should().BeFalse();
            results.IsFail().Should().BeTrue();
            results.GetException().Should().NotBeNull();
            results.GetData().Should().BeNull();
        }

        [When(@"We pass valid page attiribute but pageSize attirubute value is negative on EmegenlerPolicyRepository's Take method")]
        public void WhenWePassValidPageAttiributeButPageSizeAttirubuteValueİsNegativeOnEmegenlerPolicyRepositorySTakeMethod()
        {
            results = repo.Take(1, -1);
        }

        [Then(@"Take method should return fail status and should return Exception on negative value with pageSize attirubute from EmegenlerPolicyRepository")]
        public void ThenTakeMethodShouldReturnFailStatusAndShouldReturnExceptionOnNegativeValueWithPageSizeAttirubuteFromEmegenlerPolicyRepository()
        {
            results.IsSuccess().Should().BeFalse();
            results.IsFail().Should().BeTrue();
            results.GetException().Should().NotBeNull();
            results.GetData().Should().BeNull();
        }

        [When(@"We pass valid pageSize attirubute but page attirubute value is zero on EmegenlerPolicyRepository's Take method")]
        public void WhenWePassValidPageSizeAttirubuteButPageAttirubuteValueİsZeroOnEmegenlerPolicyRepositorySTakeMethod()
        {
            results = repo.Take(0, 1);
        }

        [Then(@"Take method should return fail status and should return Exception on zero value with page attiribute from EmegenlerPolicyRepository")]
        public void ThenTakeMethodShouldReturnFailStatusAndShouldReturnExceptionOnZeroValueWithPageAttiributeFromEmegenlerPolicyRepository()
        {
            results.IsSuccess().Should().BeFalse();
            results.IsFail().Should().BeTrue();
            results.GetException().Should().NotBeNull();
            results.GetData().Should().BeNull();
        }

        [When(@"We pass valid pageSize attiribute but page attirubute value is negative on EmegenlerPolicyRepository's Take method")]
        public void WhenWePassValidPageSizeAttiributeButPageAttirubuteValueİsNegativeOnEmegenlerPolicyRepositorySTakeMethod()
        {
            results = repo.Take(-1, 1);
        }

        [Then(@"Take method should return fail status and should return Exception on negative value with page attirubute from EmegenlerPolicyRepository")]
        public void ThenTakeMethodShouldReturnFailStatusAndShouldReturnExceptionOnNegativeValueWithPageAttirubuteFromEmegenlerPolicyRepository()
        {
            results.IsSuccess().Should().BeFalse();
            results.IsFail().Should().BeTrue();
            results.GetException().Should().NotBeNull();
            results.GetData().Should().BeNull();
        }

        [When(@"We pass valid EmegenlerPolicy entity with Id")]
        public void WhenWePassValidEmegenlerPolicyEntityWithId()
        {
            EmegenlerPolicy deletePolicy = new EmegenlerPolicy
            {
                PolicyId = 1000
            };
            result = repo.Delete(deletePolicy);
        }

        [Then(@"Delete method should return succuess status and should return deleted EmegenlerPolicy entity")]
        public void ThenDeleteMethodShouldReturnSuccuessStatusAndShouldReturnDeletedEmegenlerPolicyEntity()
        {
            result.IsSuccess().Should().BeTrue();
            result.GetData().Should().NotBeNull();
        }

        [When(@"We pass valid EmegenlerPolicy entity without Id to Delete method")]
        public void WhenWePassValidEmegenlerPolicyEntityWithoutIdToDeleteMethod()
        {
            EmegenlerPolicy deletePolicy = new EmegenlerPolicy();
            result = repo.Delete(deletePolicy);
        }

        [Then(@"Delete method should return fail status and should return Exception on EmegenlerPolicy entity without Id from EmegenlerPolicyRepository")]
        public void ThenDeleteMethodShouldReturnFailStatusAndShouldReturnExceptionOnEmegenlerPolicyEntityWithoutIdFromEmegenlerPolicyRepository()
        {
            result.IsSuccess().Should().BeFalse();
            result.IsFail().Should().BeTrue();
            result.GetException().Should().NotBeNull();
            result.GetData().Should().BeNull();
        }

        [When(@"We pass valid EmegenlerPolicy entity with Id value is equal to less than one on Delete method")]
        public void WhenWePassValidEmegenlerPolicyEntityWithIdValueİsEqualToLessThanOneOnDeleteMethod()
        {
            EmegenlerPolicy deletePolicy = new EmegenlerPolicy
            {
                PolicyId = 0
            };
            result = repo.Delete(deletePolicy);
        }

        [Then(@"Delete method should return fail status and should return Exception on EmegenlerPolicy entity with Id value is equal to less than one from EmegenlerPolicyRepository")]
        public void ThenDeleteMethodShouldReturnFailStatusAndShouldReturnExceptionOnEmegenlerPolicyEntityWithIdValueİsEqualToLessThanOneFromEmegenlerPolicyRepository()
        {
            result.IsSuccess().Should().BeFalse();
            result.IsFail().Should().BeTrue();
            result.GetException().Should().NotBeNull();
            result.GetData().Should().BeNull();
        }

        [When(@"We pass null EmegenlerPolicy entity to Delete method")]
        public void WhenWePassNullEmegenlerPolicyEntityToDeleteMethod()
        {
            result = repo.Delete(null);
        }

        [Then(@"Delete method should return fail status and should return Exception on null EmegenlerPolicy entity from EmegenlerPolicyRepository")]
        public void ThenDeleteMethodShouldReturnFailStatusAndShouldReturnExceptionOnNullEmegenlerPolicyEntityFromEmegenlerPolicyRepository()
        {
            result.IsSuccess().Should().BeFalse();
            result.IsFail().Should().BeTrue();
            result.GetException().Should().NotBeNull();
            result.GetData().Should().BeNull();
        }
        [When(@"We pass valid AuthType amd Identifier to TakePolicies method for getting User Policies")]
        public void WhenWePassValidAuthTypeAmdIdentifierToTakePoliciesMethodForGettingUserPolicies()
        {
            results = repo.TakePolicies(Guard.Emegenler.FluentInterface.Policy.Types.AuthBase.User, "1");
        }

        [Then(@"TakePolicies method should return valid List of EmegenlerPolicy entites with result success on valid AuthType amd Identifier for getting User Policies")]
        public void ThenTakePoliciesMethodShouldReturnValidListOfEmegenlerPolicyEntitesWithResultSuccessOnValidAuthTypeAmdIdentifierForGettingUserPolicies()
        {
            results.IsSuccess().Should().BeTrue();
            results.GetData().Count().Should().BeGreaterThan(0);
        }

        [When(@"We pass valid AuthType amd Identifier to TakePolicies method for getting Role Policies")]
        public void WhenWePassValidAuthTypeAmdIdentifierToTakePoliciesMethodForGettingRolePolicies()
        {
            results = repo.TakePolicies(Guard.Emegenler.FluentInterface.Policy.Types.AuthBase.Role, "Test");
        }

        [Then(@"TakePolicies method should return valid List of EmegenlerPolicy entites with result success on valid AuthType amd Identifier for getting Role Policies")]
        public void ThenTakePoliciesMethodShouldReturnValidListOfEmegenlerPolicyEntitesWithResultSuccessOnValidAuthTypeAmdIdentifierForGettingRolePolicies()
        {
            results.IsSuccess().Should().BeTrue();
            results.GetData().Count().Should().BeGreaterThan(0);
        }

        [When(@"We pass Empty value as Identifier to TakePolicies method")]
        public void WhenWePassEmptyValueAsIdentifierToTakePoliciesMethod()
        {
            results = repo.TakePolicies(Guard.Emegenler.FluentInterface.Policy.Types.AuthBase.User, "");
        }

        [Then(@"TakePolicies method should return state is fail and return Exception when Identifier is Empty")]
        public void ThenTakePoliciesMethodShouldReturnStateİsFailAndReturnExceptionWhenIdentifierİsEmpty()
        {
            results.IsSuccess().Should().BeFalse();
            results.IsFail().Should().BeTrue();
            results.GetException().Should().NotBeNull();
            results.GetData().Should().BeNull();
        }

        [When(@"We pass Null value as Identifier to TakePolicies method")]
        public void WhenWePassNullValueAsIdentifierToTakePoliciesMethod()
        {
            results = repo.TakePolicies(Guard.Emegenler.FluentInterface.Policy.Types.AuthBase.User, null);
        }

        [Then(@"TakePolicies method should return state is fail and return Exception when Identifier is Null")]
        public void ThenTakePoliciesMethodShouldReturnStateİsFailAndReturnExceptionWhenIdentifierİsNull()
        {
            results.IsSuccess().Should().BeFalse();
            results.IsFail().Should().BeTrue();
            results.GetException().Should().NotBeNull();
            results.GetData().Should().BeNull();
        }

        [When(@"We call Count method in PolicyRepository")]
        public void WhenWeCallCountMethodİnPolicyRepository()
        {
            CountOfPolicies = repo.Count();
        }

        [Then(@"Count method should return Count of Policies in EmegenlerTables")]
        public void ThenCountMethodShouldReturnCountOfPoliciesİnEmegenlerTables()
        {
            CountOfPolicies.IsSuccess().Should().BeTrue();
            CountOfPolicies.GetData().Should().BeGreaterThan(0);
        }





    }
}
